# Generated by Django 2.0.1 on 2020-07-03 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0002_auto_20200628_1415'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemname1', models.CharField(max_length=500)),
            ],
        ),
    ]
