# Generated by Django 2.0.1 on 2020-07-06 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0003_item1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item1',
        ),
    ]
