# Generated by Django 2.0.1 on 2020-07-14 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0004_delete_item1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sheet', models.IntegerField()),
                ('amount', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
