# Generated by Django 2.0.1 on 2020-07-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Items', '0007_remove_customers_customer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='active'),
        ),
    ]
